config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from kyc_sdk_api.urls import api_urls

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^api/', include(api_urls)),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^', include('dashboard.urls', namespace='dashboard', app_name='dashboard')),
    url(r'^api/dashboard/', include('dashboard.api.urls', namespace='dashboard_api', app_name='dashboard_api')),
    # User management
    # url(r'^users/', include('kyc_backend.users.urls', namespace='users')),
    # url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

dashboard/api/urls.py
from django.conf.urls import url
from .views import VerifyToggleAPIView, DeleteClientAPIView

urlpatterns = [
    url(r'^verify/$', VerifyToggleAPIView.as_view(), name='verify-toggle'),
    url(r'^delete/$', DeleteClientAPIView.as_view(), name='delete')
]

dashboard/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import reverse

from .views import home
auth_views_urls = [
    url(r'^login/$', auth_views.login, {'template_name': 'login.html', 'redirect_authenticated_user': True},
        name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': None, 'template_name': 'logged_out.html'}, name='logout'),
    url(r'^password_reset/$', auth_views.password_reset,
        {'template_name': 'password-reset.html', 'post_reset_redirect': '/password_reset/done/'},
        name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete')
]

views_url = [
    url(r'^$', home, name='home')
]

urlpatterns = auth_views_urls + views_url

users/client/models/baseclient.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from model_utils import FieldTracker
from model_utils.fields import SplitField
from django.utils.crypto import get_random_string

from model_utils.models import TimeStampedModel
from kyc_backend.utils import pkgen, update_filename

from django.utils.timezone import now


class BaseClient(TimeStampedModel):
    GENDER = (
        (0, 'Male'),
        (1, 'FEMale')
    )
    RELIGION = (
        (0, 'Muslim'),
        (1, 'Christian'),
        (2, 'Jewish'),
    )
    STATUS = (
        (0, 'Single'),
        (1, 'Married'),
        (2, 'Divorced')
    )
    is_valid = models.BooleanField(default=False, verbose_name="Valid data")
    face_img = models.ImageField(upload_to=update_filename, null=True)
    mobile_no = models.CharField(max_length=11, null=True)
    full_name = models.CharField(max_length=128, null=True)
    address = models.CharField(null=True, max_length=256)
    national_id = models.CharField(max_length=14, null=True)
    gender = models.PositiveSmallIntegerField(choices=GENDER, default=0, null=True)
    religion = models.PositiveSmallIntegerField(choices=RELIGION, default=0, null=True)
    status = models.PositiveSmallIntegerField(choices=STATUS, default=0, null=True)
    work = models.CharField(max_length=256, default=0)
    ref = models.CharField(default=pkgen, max_length=10, unique=True)
    tracker = FieldTracker(fields=['mobile_no', 'address', 'is_seen'])
    is_kyc = models.BooleanField(default=False)
    otp = models.CharField(max_length=6, null=True)
    otp_timer = models.DateTimeField(null=True)
    available_mobile_no = ArrayField(models.CharField(max_length=11), size=10, null=True, default=[])

    def generate_otp(self):
        otp = get_random_string(length=6, allowed_chars='0123456789')
        self.otp = otp
        self.otp_timer = now()
        self.save()
        return otp

    def check_otp(self, otp):
        return self.otp == otp and (now() - self.otp_timer).total_seconds() < 901

    class Meta:
        abstract = True

users/client/models/client.py
from django.db import models

from kyc_backend.utils import update_filename
from .baseclient import BaseClient
from django.utils.crypto import get_random_string
from django.utils.timezone import now

class ClientManager(models.Manager):
    def unseen(self):
        query = self.get_queryset()
        return query.filter(is_seen=False)

class Client(BaseClient):
    entity = models.ForeignKey("service_provider.Entity", related_name='clients')
    no_of_sendings = models.PositiveSmallIntegerField(default=0)
    mobile_device = models.OneToOneField('client.MobileDevice', null=True)
    is_seen = models.BooleanField(default=False, verbose_name="Is verified by entity?")
    objects = ClientManager()
    id_back_img = models.ImageField(upload_to=update_filename, null=True)
    id_front_img = models.ImageField(upload_to=update_filename, null=True)

    def verify(self, face_text, back_text):
        self.is_kyc = True
        self.save()
        return True

    def send_sms(self):
        pass

    def generate_otp(self):
        otp = get_random_string(length=6, allowed_chars='0123456789')
        self.otp = otp
        self.otp_timer = now()
        self.no_of_sendings += 1
        self.save()
        return otp

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if self.is_seen and self.is_valid:
            self.is_kyc = True
        super(Client, self).save(force_insert, force_update, using, update_fields)

    def delete(self, using=None, keep_parents=False):
        self.entity.license.retrieve_license() if not self.is_valid else None
        super(Client, self).delete(using, keep_parents)

users/client/models/merchant.py
from .baseclient import BaseClient


class Merchant(BaseClient):
    pass

users/client/models/mobiledevice.py
from uuid import uuid4

from django.db import models
from django.utils.translation import ugettext_lazy as _


class MobileDevice(models.Model):
    """
    Model to extend while creating your custom Devices model for your
    project. By default, this offers the bare-minimum fields to register push-enabled devices,
    register them on AWS SNS and store this information in the database.
    """

    APN = 'apn'
    GCM = 'gcm'
    DEVICE_TYPES = (
        (APN, 'APN'),
        (GCM, 'GCM')
    )

    id = models.UUIDField(
        primary_key=True,
        unique=True,
        default=uuid4
    )
    device_type = models.CharField(
        verbose_name='Push Device Type',
        max_length=5, choices=DEVICE_TYPES,
        default=APN, help_text=_('APN or GCM')
    )

    @property
    def is_ios(self):
        return True if self.push_device_type == self.APN else False

    @property
    def is_android(self):
        return True if self.push_device_type == self.GCM else False

users/client/views.py
from django.shortcuts import render

# Create your views here.

kyc_backend/templates/clients.html
{% extends 'base.html' %}
{% block title %}Clients{% endblock %}
{% block content %}
    <div class="row">
    <section class="content container-fluid">
    <div class="row">
        <div class="col-lg-offset-1 col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-green">
            <div class="inner">
              <h3>{{ kyc_count }}<sup style="font-size: 20px">kyc</sup></h3>

              <p>Clients</p>
            </div>
            <div class="icon">
              <i class="ion ion-person-add"></i>
            </div>
            <a href="#" class="small-box-footer">
              More info <i class="fa fa-arrow-circle-right"></i>
            </a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-yellow">
            <div class="inner">
              <h3>{{ valid_count }}</h3>

              <p>Valified Clients</p>
            </div>
            <div class="icon">
              <i class="ion ion-checkmark"></i>
            </div>
            <a href="#" class="small-box-footer">
              More info <i class="fa fa-arrow-circle-right"></i>
            </a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-red">
            <div class="inner">
              <h3>{{ unseen_count }}</h3>

              <p>Unverified clients</p>
            </div>
            <div class="icon">
              <i class="ion ion-pie-graph"></i>
            </div>
            <a href="#" class="small-box-footer">
              More info <i class="fa fa-arrow-circle-right"></i>
            </a>
          </div>
        </div>
        <!-- ./col -->
      </div>
    </section>
      <!-- /.row -->
    </div>

    <div class="row">
        {% for client in clients %}
        <div class="col-xs-offset-1 col-xs-10 col-md-offset-0 col-md-4">
          <!-- Widget: user widget style 1 -->
          <div class="box box-widget widget-user-2">
            <!-- Add the bg color to the header using any of the bg-* classes -->

            {% if client.is_seen %}
                <div class="widget-user-header bg-yellow">
                <div class="box-tools pull-right">
                    <a class="btn btn-app verify-btn" data-href="{{ client.ref }}">
                      <i class="fa fa-thumbs-down"></i> UnVerify
                    </a>
                </div>
            {% else %}
                <div class="widget-user-header bg-red-active">
                <div class="box-tools pull-right">
                    <a class="btn btn-app verify-btn" data-href="{{ client.ref }}">
                    <i class="fa fa-thumbs-up"></i> Verify
                  </a>

                </div>

            {% endif %}
                <div class="box-tools pull-right">
                    <a class="btn btn-app delete-btn" data-href="{{ client.ref }}">
                      <i class="fa fa-trash"></i> Delete
                    </a>
                </div>
              <div class="widget-user-image" >
                <img class="img-circle profile-pic" style="max-height: 80px" src="{{ MEDIA_URL }}{{ client.face_img }}" alt="User Face" data-toggle="modal" data-target="#modal-success" onclick='document.getElementById("img01").src="{{ MEDIA_URL }}{{ client.face_img }}"; document.getElementById("modal-title").innerText="#{{ client.ref }}"'>
              </div>
              <!-- /.widget-user-image -->
              <h3 class="widget-user-username">#{{ client.ref }}</h3>
              <h5 class="widget-user-desc">{{ client.created }}</h5>

            </div>

            <div class="box-footer no-padding">
              <ul class="nav nav-stacked">
                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>#</b> {{ client.national_id }}</li>
                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Name</b> {{ client.full_name }}</li>
                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Address</b> {{ client.address }}</li>
                  <li></li>
              </ul>
                <div class="row">
                <div class="col-sm-4 border-right">
                  <div class="description-block">
                    {% ifequal client.gender 0 %}
                      <h5 class="description-header">Male</h5>
                      <span class="description-text"><i class="fa fa-mars"></i></span>
                    {% else %}
                        <h5 class="description-header">Female</h5>
                      <span class="description-text"><i class="fa fa-venus"></i></span>
                    {% endifequal %}
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-4 border-right">
                  <div class="description-block">
                    {% ifequal client.gender 0 %}
                      <h5 class="description-header">Muslim</h5>
                    {% endifequal %}
                    {% ifequal client.gender 1 %}
                        <h5 class="description-header">Christian</h5>
                    {% endifequal %}
                    {% ifequal client.gender 2 %}
                        <h5 class="description-header">Jewish</h5>
                    {% endifequal %}
                    <span class="description-text"><i class="fa fa-hands"></i>Religion</span>

                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-4">
                  <div class="description-block">
                      {% ifequal client.status 0 %}
                        <h5 class="description-header">Single</h5>
                      {% endifequal %}
                      {% ifequal client.status 1 %}
                          <h5 class="description-header">Married</h5>
                      {% endifequal %}
                    {% ifequal client.status 2 %}
                        <h5 class="description-header">Divorced</h5>
                    {% endifequal %}

                    <span class="description-text">Status</span>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
              </div>
            <div class="row">
                <div class="col-sm-6 border-right">
                  <div class="description-block">
                      <h5 class="description-header">Front</h5>
                <img class="text-center img-thumbnail" src="{{ MEDIA_URL }}{{ client.id_front_img }}" alt="Front Face" data-toggle="modal" data-target="#modal-success" onclick='document.getElementById("img01").src="{{ MEDIA_URL }}{{ client.id_front_img }}"; document.getElementById("modal-title").innerText="#{{ client.ref }}"'>

                  </div>
                  <!-- /.description-block -->
                </div>
                <div class="col-sm-6 border-right">
                  <div class="description-block">

                        <h5 class="description-header">Back</h5>
                <img class="text-center img-thumbnail" src="{{ MEDIA_URL }}{{ client.id_back_img }}" alt="Back Face" data-toggle="modal" data-target="#modal-success" onclick='document.getElementById("img01").src="{{ MEDIA_URL }}{{ client.id_back_img }}"; document.getElementById("modal-title").innerText="#{{ client.ref }}"'>
                  </div>
                  <!-- /.description-block -->
                </div>
            </div>
            </div>
          </div>
          <!-- /.widget-user -->
        </div>
        {% endfor %}
    </div>
<div class="modal modal-warning fade" id="modal-success">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal-title"></h4>
              </div>
              <div class="modal-body">
                <img class="modal-content img-responsive" id="img01">
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>
              </div>
            </div>
            <!-- /.modal-content -->
          </div>
          <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
    <div class="modal modal-warning fade" id="modal-delete">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal-title">Delete Success</h4>
              </div>
              <div class="modal-body">
                The client has been deleted successfully
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>
              </div>
            </div>
            <!-- /.modal-content -->
          </div>
          <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->

{% endblock %}
{% block extrastylesheet %}
    <style type="text/css">
    .btn-app {
        position: relative;
        padding: 15px 5px;
        margin: 0 0 10px 10px;
        min-width: 30px;
        height: 60px;
        text-align: center;
        color: ghostwhite;
        background-color: transparent;
        border-color: transparent;
        font-size: 12px;
    }
    .btn-app:hover {
        opacity: 0.7;
        border-color: transparent;
        color: whitesmoke;
        background-color: transparent;

    }
    </style>
{% endblock %}
{% block customscript %}
    <script>

    $('.verify-btn').click(function (event) {
        event.preventDefault();
        var _this = $(this);
        var div_par = _this.parent().parent();
        if(confirm("Are you sure to verify/unverify client")){
        $.ajax({
            url: '{% url "dashboard_api:verify-toggle" %}',
            method: "GET",
            data: {ref: _this.data("href")},
            cache:false,

            success: function (data) {
                console.log(data);
                if (data.verify){
                    _this.html("<i class='fa fa-thumbs-down'></i> UnVerify");
                    div_par.removeClass("bg-red-active").addClass("bg-yellow");

                }
                else{
                    _this.html("<i class='fa fa-thumbs-up'></i> Verify");
                    div_par.removeClass("bg-yellow").addClass("bg-red-active");
                }
            },
            error: function (xhr,status,error) {
                console.log(xhr);
                console.log(status);
                console.log(JSON.stringify(error));
            }
        });
        }
    });
    $('.delete-btn').click(function (event) {
        event.preventDefault();
        var _this = $(this);
        var div_par = _this.parent().parent().parent().parent();
        if(confirm("Are you sure to delete client")){
        $.ajax({
            url: '{% url "dashboard_api:delete" %}',
            method: "DELETE",
            data: {ref: _this.data("href")},
            cache:false,

            success: function (data) {
                div_par.remove();
                $('#modal-delete').modal('show');
            },
            error: function (xhr,status,error) {
                console.log(xhr);
                console.log(status);
                console.log(JSON.stringify(error));
            }
        });
        }
    });

    </script>
{% endblock %}

kyc_backend/templates/login.html
{% load cssclass %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Valify | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="../static/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="../static/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="../static/bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../static/dist/css/AdminLTE.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="../static/plugins/iCheck/square/blue.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="#"><b>Valify</b>.CO</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>

    <form action="{% url 'dashboard:login' %}" method="post">
        {% csrf_token %}
      <div class="form-group has-feedback">
        {{ form.username | addclass:'form-control' }}
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
          {{ form.password | addclass:'form-control' }}
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

    <a href="{% url 'dashboard:password_reset' %}">I forgot my password</a><br>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="../static/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="../static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="../static/plugins/iCheck/icheck.min.js"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>

kyc_backend/templates/password-reset.html
{% load cssclass %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Valify | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="../static/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="../static/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="../static/bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../static/dist/css/AdminLTE.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="../static/plugins/iCheck/square/blue.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="#"><b>Valify</b>.CO</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Insert your email to send you reset password link</p>

    <form action="." method="post">
        {% csrf_token %}
      <div class="form-group has-feedback">
        {{ form.email | addclass:'form-control' }}
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>

      <div class="row">
        <!-- /.col -->
        <div class="col-xs-offset-8 col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Send</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="../static/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="../static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="../static/plugins/iCheck/icheck.min.js"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>

kyc_backend/templates/register.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Registration Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="../../bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="../../bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="../../bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../../dist/css/AdminLTE.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="../../plugins/iCheck/square/blue.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>

  <div class="register-box-body">
    <p class="login-box-msg">Register a new membership</p>

    <form action="../../index.html" method="post">
      <div class="form-group has-feedback">
        <input type="text" class="form-control" placeholder="Full name">
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="email" class="form-control" placeholder="Email">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Retype password">
        <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> I agree to the <a href="#">terms</a>
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

    <div class="social-auth-links text-center">
      <p>- OR -</p>
      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign up using
        Facebook</a>
      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign up using
        Google+</a>
    </div>

    <a href="login.html" class="text-center">I already have a membership</a>
  </div>
  <!-- /.form-box -->
</div>
<!-- /.register-box -->

<!-- jQuery 3 -->
<script src="../../bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="../../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="../../plugins/iCheck/icheck.min.js"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>